services:
  - type: web
    name: skin-cancer-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    runtime: python
    pythonVersion: "3.11.0"